### ISSUE TITLE
Add alternative for _.difference()

### ISSUE THREAD

**Issue by EvHaus** [reindexio/youmightnotneedunderscore#15]
```
// Underscore
_.uniq(array);

// ES2015
[...new Set(array)]
```

```
// Underscore
_.difference(a, b);

// ES2015
const aSet = new Set(a);
const bSet = new Set(b);
const result = [...new Set([...aSet].filter((x) => !bSet.has(x)))];
```

**Comment by fson** [comment]
The `uniq` example we already have: https://github.com/reindexio/youmightnotneedunderscore#create-a-copy-of-an-array-with-duplicates-removed

Not sure about the `difference` example, looks quite complex. The idea is to show examples where using the standard library doesn't add complexity – preferably cases where the code can be written with a single expression or method call. Maybe it could be simplified a bit:

``` js
const set = new Set(b);
const result = [...new Set(a.filter((x) => !set.has(x)))];
```

But still, if you need the result as an array like in the Underscore example, this is still not very straightforward.

**Comment by EvHaus** [comment]
Sure, you can "simplify" it to one line, but it becomes quite unreadable.

```
[...new Set([...new Set(a)].filter((x) => !(new Set(b)).has(x)))];
```

**Comment by fson** [comment]
I think you don't need to convert `a` to a `Set` first.

Anyway, while this is a handy code snippet, it isn't an example of something that's particularly easy to do in ES2015, and therefore not a good fit for this collection. Thanks for the suggestion!
